name: pbs
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  camera: ^0.10.5+9
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  permission_handler: ^11.3.0
  google_mlkit_commons: ^0.6.1
  google_mlkit_barcode_scanning: ^0.10.0
  image: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/barcode.jpg
    - assets/images/impact_logo.png
